name: Playwright Tests
run-name: "Test - ${{ 
          (github.event.schedule == '00 18 * * *' && 'Regresion Automatic' ) || 
          (github.event.schedule == '* * * * 1-5' && 'Smoke Automatic' ) || 
          format('Manual de tipo: {0}',inputs.type) 
          }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: '
        required: true
        default: 'develop'
        type: choice
        options:
          - 'develop'
          - 'staging'
          - 'qa'
          - 'production'
      tags:
        description: 'Test scenario tags: @tag_name'
        default: '@smoke'
        required: true
        type: string
      browser:
        description: 'Browser: '
        required: true
        default: 'chromium'
        type: choice
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'
  schedule:
      # Regression
    - cron: "00 18 * * *"
      # Smoke
    #- cron: "0 4 * * 1-5"
    - cron: "* * * * 1-5"

  pull_request:
    branches: [ main, develop ]

jobs:

  create-matrix:
    name: Create Matrix
    runs-on: [self-hosted]
    outputs:
      infoExecution: ${{ steps.matrix.outputs.matrix }}
    
    steps:
      
      - uses: actions/checkout@v6

      - name: Create Matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
          
            case '${{ github.event.schedule }}' in
            "00 18 * * *")
              echo '${{ vars.REGRESSION }}' > regression.json
              ;;
            "* * * * 1-5")
              echo '${{ vars.SMOKE }}' > regression.json
              ;;
            esac
          
            python .github/workflows/utils/create_strategy_array.py
            MATRIX=$(cat regression.json)
            MATRIX="${MATRIX//'%'/'%25'}"
            MATRIX="${MATRIX//$'\n'/'%0A'}"
            MATRIX="${MATRIX//$'\r'/'%0D'}"
          else
            MATRIX='[{"type": "${{ inputs.type }}", "environment": "${{ inputs.environment }}", "browser":"${{ inputs.browser }}" "tags": "${{ inputs.execute_tags }}"}]'
          fi
          echo "::notice title=Execution matrix::${MATRIX}"
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  test:
    needs: create-matrix
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        executions: ${{ fromJson(needs.create-matrix.outputs.infoExecution) }}

    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      GREP: ${{ inputs.tags || '@smoke' }}
      PROJECT: ${{ inputs.browser || 'chromium' }}
    steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          ENVIRONMENT: ${{ matrix.executions.environment == 'develop' && '' || matrix.executions.environment }}
      run: pnpm bddgen && pnpm playwright test --grep ${{ matrix.executions.tags }}  --project=${{ matrix.executions.browser }}

    - uses: actions/upload-artifact@v7

      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
